services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"

  api:
    build: .
    container_name: gemma-api
    ports:
      - "8000:8000"
    depends_on:
      - ollama

volumes:
  ollama_data: